/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab12storybook;

/**
 *
 * @author Rahul Gawdi
 */
public class EndFrame extends javax.swing.JFrame {

   private StoryBookModel myModel;
    //private String StoryBookModel;
    private Boolean exit = false;
    private Boolean next = false;
    /**
     * Creates new form EndFrame
     */
    public EndFrame() {
        initComponents();
    }
 EndFrame(StoryBookModel myModel) {
        this.myModel = myModel;
       initComponents();
      WelcomeLabel.setText("Welcome, " + myModel.getUserName() + ".");
      CrimeLabel1.setText("You have been accused of: " + myModel.getCrime() + ".");
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        CrimeLabel1 = new javax.swing.JLabel();
        InstructionLabel = new javax.swing.JLabel();
        LeftDoorButton = new javax.swing.JButton();
        RightDoorButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeLabel.setText("Welcome");

        CrimeLabel1.setText("jLabel1");

        InstructionLabel.setText("Pick A Door to Determine Your Verdict.");

        LeftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab12storybook/Door.GIF"))); // NOI18N
        LeftDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftDoorButtonActionPerformed(evt);
            }
        });

        RightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab12storybook/Door.GIF"))); // NOI18N
        RightDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightDoorButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit Tribunal");
        ExitButton.setEnabled(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        NextButton.setText("Next Trial -->");
        NextButton.setEnabled(false);
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeLabel)
                    .addComponent(InstructionLabel)
                    .addComponent(CrimeLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(LeftDoorButton)
                        .addGap(61, 61, 61)
                        .addComponent(RightDoorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(ExitButton)
                        .addGap(72, 72, 72)
                        .addComponent(NextButton)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WelcomeLabel)
                .addGap(26, 26, 26)
                .addComponent(CrimeLabel1)
                .addGap(30, 30, 30)
                .addComponent(InstructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeftDoorButton)
                    .addComponent(RightDoorButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(NextButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LeftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftDoorButtonActionPerformed
        // TODO add your handling code here:
                LeftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab12storybook/Tiger.GIF")));
                InstructionLabel.setText("YOU ARE GUILTY, PREPARE TO BE EATEN!");
                RightDoorButton.setEnabled(false);
                NextButton.setEnabled(true);
                ExitButton.setEnabled(true);
    }//GEN-LAST:event_LeftDoorButtonActionPerformed

    private void RightDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightDoorButtonActionPerformed
        // TODO add your handling code here:
        RightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab12storybook/Lady.GIF")));
                InstructionLabel.setText("You are Innocent! Sorry about that! Please accept this Lady.");
                LeftDoorButton.setEnabled(false);
                 NextButton.setEnabled(true);
                ExitButton.setEnabled(true);
    }//GEN-LAST:event_RightDoorButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        StartFrame storyBookModel = new StartFrame(myModel);
        storyBookModel.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_NextButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   
        /* Create and display the form */
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CrimeLabel1;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel InstructionLabel;
    private javax.swing.JButton LeftDoorButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton RightDoorButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
